FROM mongo:jammy

# MongoDB is used to save the code execution result that has been consumed 
# from RCE Engine Service for persistence. 
# The result is cached in redis, and saved in mongodb.  

WORKDIR /data/db


