# Generated by Django 4.2.11 on 2024-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("code_display", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="Questions/Images",
                verbose_name="Related Imgae to the Question",
            ),
        ),
    ]
