# Generated by Django 4.2.11 on 2024-05-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("code_display", "0002_questions_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="acceptence_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
