# Generated by Django 4.2.11 on 2024-05-01 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("code_display", "0003_questions_acceptence_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="acceptence_rate",
            new_name="acceptance_rate",
        ),
    ]
