# Generated by Django 4.2.11 on 2024-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("code_display", "0004_rename_acceptence_rate_questions_acceptance_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="image",
            field=models.ImageField(
                default="Questions/Images/dsa.png",
                upload_to="Questions/Images",
                verbose_name="Related Imgae to the Question",
            ),
        ),
    ]
